Week3 val
learn-academy-2023-bravo/week-3-assessment-ValC001 pull request #1
Opened 2023-04-03 18:28 UTC by ValC001

# Submitting Week 3 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ ] Interview Questions
- [ ] React Debugging

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-04-03 21:52 UTC, Genemichael25 requested changes
Valeria, I am requesting changes for the missing pseudocode and attempts on code challenges # 1 and 3. Please let me know when you have made the changes so that I can finish reviewing your assessment. Thanks

2023-04-03 21:52 UTC, Genemichael25 commented on code-challenges.test.js
> +// Pseudo Code
Missing pseudocode and function attempt for number 1.

2023-04-03 21:52 UTC, Genemichael25 commented on code-challenges.test.js
> +// // b) Create the function that makes the test pass.
Same as # 1, pseudocode and function attempt.

2023-04-07 02:29 UTC, SunkissedQueen requested changes
Missing function on 1b

2023-04-07 02:29 UTC, SunkissedQueen commented on code-challenges.test.js
> +// })
The test and the function should not be commented out. They need to be visible for the test suite to see both.

2023-04-07 02:29 UTC, SunkissedQueen commented on code-challenges.test.js
> +
should not be commented out

2023-04-07 02:29 UTC, SunkissedQueen commented on code-challenges.test.js
> +
missing the function

2023-04-07 21:00 UTC, SunkissedQueen approved these changes
Valeria, thanks for providing the changes. I appreciate that you are working through your novice skillsets. I am glad that you have accepted mentorship. Suggestions on things to work on: Pseudocode, Functions, and Content for interview questions.
Your tests have good structure. It looks like you need more content in your pseudocode about the data so you can create your function properly. Let's try to meet up and discuss more strategies that can support you as you are learning to develop.
Next assessment: provide more content on the pseudocode and your interview answers. With practice and knowledge of your blockers, you can be at advanced beginner by internship.

2023-04-07 21:03 UTC, ValC001 commented
Done

2023-04-07 21:03 UTC, merged